components/footer.tsx, components/header.tsx, constants/footer.ts, constants/header.ts
- Implemented an indicator for external links to distinguish them from internal ones.  
- Added functionality to open external links in a new tab for improved user experience.
=> Add External Link Indicator and Support for Opening in New Tab

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/workflows/build.yml, .github/workflows/lint.yml
- Updated issue templates to ensure consistency and gather additional data.
- Modified GitHub workflows to support Ubuntu 24.04 and improved caching.
=> Update Issue Templates and GitHub Workflows

components/Footer.tsx, constants/footer.ts
=> refactor: streamline footer component layout and constants

locales/pl/translation.json
- Engine in Polish is a masculine word, so it should be stabiln**y** not stabiln**e** (neutral).
=> Refactor: Fixed a typo in pl/translation.json

app/layout.tsx
=> feat: enhance site metadata for better SEO and social sharing

app/layout.tsx
=> chore: remove Google verification metadata

.github/actions/install/action.yml, .github/labeler.yml, .github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/pr-coauthor.yml, .github/workflows/pr-labeler.yml, .github/workflows/welcome-bot.yml
=> Add GitHub Workflows 

CONTRIBUTING.md, README.md
- [ O ] I have read and understood the [Contributor Guidelines](https://github.com/Redot-Engine/redot-website/blob/master/CONTRIBUTING.md).
- [ O ] I have verified that there are no duplicate pull requests for this request.
- [ O ] I believe this submission is valuable to others.
- [ O ] I acknowledge that this submission may not be used and the pull request may be closed at the maintainers' discretion.
- Documentation about development environmental variables
=> docs: add development .env instruction

constants/socials.tsx
=> Update Discord Image URL to Use Invite Link with .webp Format

locales/ar/translation.json, locales/el/translation.json
Adding translation for ar and el
**Related issues (if any):**
#94 
**Screenshots (if applicable):**
=> fix: ar and el translation

locales/pl/translation.json
- [yes] I have read and understood the [Contributor Guidelines](https://github.com/Redot-Engine/redot-website/blob/master/CONTRIBUTING.md).
- [yes] I have verified that there are no duplicate pull requests for this request.
- [yes] I believe this submission is valuable to others.
- [yes] I acknowledge that this submission may not be used and the pull request may be closed at the maintainers' discretion.
Full Polish translation of official Redot website
=> chore:polish translation

.github/labeler.yml, .github/pull-request-template.md, .github/workflows/ci.yml, README.md
- Updated the pull request template to ensure consistency in the "Additional Notes" section.
- Added the 'fix' label to the labeler configuration to enhance issue tracking.
- Updated the CI workflow to use environment variables for Sanity configuration.
- Removed outdated Node.js installation instructions from the README.
=> Update Template, Labeler, CI Workflow, and README

app/(main)/privacy/page.tsx, app/(main)/terms/page.tsx, components/blog/ArticleSplashOld.tsx
This commit adds padding to the `ArticleSplashOld` component to enhance the overall layout and improve the visual appearance. The added padding ensures better spacing around the content, resulting in a cleaner and more readable design.
=> Add Padding to `ArticleSplashOld` Component for Improved Layout

app/(main)/privacy/page.tsx, app/(main)/terms/page.tsx, components/blog/ArticleCard.tsx, components/blog/ArticleSplashNew.tsx, components/sections/blog/BlogClient.tsx, components/sections/blog/LatestBlogHero.tsx, components/sections/landing/Blog.tsx
- Improved layout and styling of the `LatestBlogHero` component to enhance readability.  
- Simplified the `ArticleCard` component for better layout consistency across the app.  
- Updated title styling in the `ArticleSplashNew` component to align with the overall design system.  
- Removed redundant classes from the `TextFetcher` used in terms and privacy pages for cleaner code.
=> Enhance Blog Layout and Styling Consistency

locales/de/translation.json
- [ x] I have read and understood the [Contributor Guidelines](https://github.com/Redot-Engine/redot-website/blob/master/CONTRIBUTING.md).
- [x ] I have verified that there are no duplicate pull requests for this request.
- [x ] I believe this submission is valuable to others.
- [x ] I acknowledge that this submission may not be used and the pull request may be closed at the maintainers' discretion.
Made translation more consistent and accurate + fixing small mistakes.
**Related issues (if any):**
**Screenshots (if applicable):**
**Additional notes:**
=> fix: DE translation

app/api/download/route.ts
Mac OS latest download was not working due to file name differences.
**Related issues (if any):**
**Screenshots (if applicable):**
**Additional notes:**
Fixed regex
=> fix: download

app/(main)/page.tsx
Super secret update page.tsx
Super secret update page.tsx
Super secret update page.tsx
Super secret update page.tsx
=> Super secret update page.tsx

app/(main)/page.tsx
Reverts Redot-Engine/redot-website#146
=> Revert "Super secret update page.tsx"

components/CookieConsent.tsx
**PR Description:**  
This PR enhances the Cookie Consent component by improving accessibility with ARIA attributes and updating the cookie handling logic for better security and compliance. It also introduces `onAcceptCallback` and `onDeclineCallback` props to allow customizable actions on cookie consent decisions. UI updates include improved button styling and better semantic structure for screen readers.  
**Screenshots:**
=> Improve Cookie Consent Accessibility and Add Callbacks

app/(main)/contact/page.tsx, components/contact/ContactCard.tsx, components/shared/animations.ts
This pull request introduces several enhancements and fixes to the Contact page, aiming to improve user experience and functionality.
**Screenshots (if applicable):**
New
Old
=> Improve Contact Page Layout and Add Visual Enhancements

app/(main)/community/page.tsx, components/community/CommunityCard.tsx, components/community/CommunitySection.tsx
This pull request improves the animations and layout of the `Community` page by refactoring existing code and enhancing the user experience with more dynamic transitions. The changes also include cleaning up redundant code and optimizing the grid layout for better responsiveness.
=> Refactor and Enhance Community Page Animations

app/(main)/download/[platform]/page.tsx, app/(main)/download/page.tsx, components/sections/landing/Hero.tsx, constants/download/platforms.ts, hooks/use-os.tsx
This pull request refactors the OS detection hook in hooks/use-os.tsx.
=> Refactor OS Detection Hook

.dev.vars, .gitignore, app/api/download/route.ts, app/api/feed.xml/route.ts, app/api/mirrorlists/[mirrorlist]/route.ts, app/layout.tsx, app/not-found.tsx, bun.lock, open-next.config.ts, package.json, public/_headers, wrangler.jsonc
- Added scripts for preview, deploy, upload, and type generation using opennextjs-cloudflare and wrangler
- Switched to @opennextjs/cloudflare for deployment
- Removed @cloudflare/next-on-pages dependency
- Added wrangler to devDependencies
- Remove edge runtime export
=> [WIP] Cloadflare Workers 
